# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 500

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Joint Trajectory Controller - effort based -------------------------------
torque_base_pos_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: *robot_joints
  gains: # Required because we're controlling an effort interface
    shoulder_pan_joint: {p: 75,  d: 2, i: 0.5, i_clamp: 5}
    shoulder_lift_joint: {p: 75,  d: 2, i: 0.5, i_clamp: 5}
    elbow_joint: {p: 75,  d: 2, i: 0.5, i_clamp: 5}
    wrist_1_joint: {p: 8,  d: 1, i: 0.2, i_clamp: 2}
    wrist_2_joint: {p: 8,  d: 1, i: 0.2, i_clamp: 2}
    wrist_3_joint: {p: 8,  d: 1, i: 0.2, i_clamp: 2}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
    shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
    elbow_joint: {trajectory: 0.2, goal: 0.1}
    wrist_1_joint: {trajectory: 0.2, goal: 0.1}
    wrist_2_joint: {trajectory: 0.2, goal: 0.1}
    wrist_3_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20


# Individual joint velocity controllers for direct velocity control
torque_base_shoulder_pan_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: shoulder_pan_joint
  pid: {p: 50, d: 0.2, i: 0.02, i_clamp: 0.5}

torque_base_shoulder_lift_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: shoulder_lift_joint
  pid: {p: 50, d: 0.2, i: 0.02, i_clamp: 0.5}

torque_base_elbow_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: elbow_joint
  pid: {p: 50, d: 0.2, i: 0.02, i_clamp: 0.5}

torque_base_wrist_1_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: wrist_1_joint
  pid: {p: 20, d: 0.1, i: 0.01, i_clamp: 0.2}

torque_base_wrist_2_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: wrist_2_joint
  pid: {p: 10, d: 0.1, i: 0.01, i_clamp: 0.2}

torque_base_wrist_3_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joint: wrist_3_joint
  pid: {p: 15, d: 0.1, i: 0.01, i_clamp: 0.2}

